language: c

sudo: false

env:
  - ARCH=i686
    LUA="lua 5.1" 

before_install:
  - pip install --user cpp-coveralls hererocks
  - hererocks env --$LUA --luarocks latest
  - export PATH="$PWD:$PATH"
  - export PATH="$PWD/env/bin:$PATH"
  - export LIDE_PATH="$PWD"
  - luarocks install luafilesystem

install:
  - luarocks install https://raw.githubusercontent.com/lidesdk/framework/master/lide-0.0-0.rockspec

script:
  - lua tests/init_tests.lua

after_success:
  # - coveralls -b . -i src --dump c.report.json
  # - luacov-coveralls -j c.report.json -v

notifications:
  email:
    on_success: change
    on_failure: always
